---
abstract: 'date and time succinctly'
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
build_requires:
  Module::Build: 0.34
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-dt
provides:
  Time::Piece::Tidy:
    file: lib/Time/dt.pm
  Time::dt:
    file: lib/Time/dt.pm
    version: v0.0.1
requires:
  Time::Piece: 1.20
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Time-dt
  homepage: http://enobacon.com/
  license: http://dev.perl.org/licenses/
  repository: git://git.enobacon.com/Time-dt.pm.git
version: v0.0.1
